POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1vbnN0ZXIiLCJpZCI6IjYyYTMxN2VkMDc0ZjBkMWIzMDRiY2Y2NCIsImlhdCI6MTY1NDg1NzgzNiwiZXhwIjoxNjU0ODYxNDM2fQ.6V1QK35YIIrocbty4wS3WcpRTqBaqrfC-bkeBR6BvaY

{
  "title": "Hilfe! Das monstrum in mir wird explodieren",
  "author": "Johan",
  "url": "www.facebook.com",
  "likes": 20
}